### ISSUE TITLE
Data description

### ISSUE THREAD

**Issue by adiferd** [maniteja123/defect_prediction#1]
Hi @maniteja123 , would you mind to make description about your testing data?

**Comment by maniteja123** [comment]
Hi @adiferd , would be happy to share. The data was the number of  bug reports on open source software like firefox, eclipse etc. over a span of releases. 
The attempt was to fit statistical models to the data for previous releases and predict the expected number of bug reports for the future releases. Hope it helps. Thanks for your interest.
